# config.py — All constants, watchlist, and filter parameters

SYMBOLS = [
    "YESBANK", "SUZLON", "IDEA", "IRFC", "NHPC",
    "RECLTD", "PFC", "RVNL", "IREDA", "SJVN",
    "PNBHOUSING", "BANKINDIA", "UNIONBANK", "CANBK", "IOB",
    "NATIONALUM", "SAIL", "NMDC", "COALINDIA", "GMRINFRA"
]

EXCHANGE = "NSE"
PRICE_MIN = 20
PRICE_MAX = 150
AVG_VOLUME_MIN = 1_000_000
VOLUME_SURGE_MULTIPLIER = 3
RSI_MIN = 60
RSI_MAX = 80
STOP_LOSS_PCT = 0.05
TAKE_PROFIT_PCT = 0.20
RSI_PERIOD = 14
EMA_PERIOD = 50
VOLUME_AVG_PERIOD = 20
WEEK52_PERIOD = 252
REFRESH_INTERVAL_SECONDS = 30
DEQUE_MAXLEN = 390  # 1 full trading day of 1-min bars
