name: Python Package using Conda
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base

      - name: Lint with flake8
        run: |
          conda install -y flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings; adjust max-line-length to your preference
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # No tests yet: avoid failing the pipeline with pytest exit code 5 (no tests collected)
      - name: Skip tests (no suite yet)
        run: echo "No tests; skipping pytest"
